server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
management:
  security:
    enabled: false
